let fname:string ="MUKUL";
let lname:string ="KUMAR";
let fullname:string =`${fname}`+" "+`${lname}`;
let fullname2:string = fname+" "+lname;
console.log(fname);
console.log(lname);
console.log(fullname);
console.log(fullname2);
console.log(fname.charAt(2));
console.log(fullname.lastIndexOf('r'));