var fname = "MUKUL";
var lname = "KUMAR";
var fullname = "".concat(fname) + " " + "".concat(lname);
var fullname2 = fname + " " + lname;
console.log(fname);
console.log(lname);
console.log(fullname);
console.log(fullname2);
console.log(fname.charAt(2));
console.log(fullname.lastIndexOf('r'));
